name: ble_parser
description: A Flutter package for parsing BLE data from wearable devices.
version: 1.0.0
homepage:

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^2.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: